name: Build & Deploy CooksCorner Project

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy CooksCorner Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build the application
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: Build Docker image with Dockerfile
        env:
        DOCKER_FILE: Dockerfile
        run: |
          mv build/${DOCKER_FILE} /tmp/dockerfile
          docker build -t docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/cookscorner_repo_docker:latest --file /tmp/dockerfile .

      - name: Push Docker image to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Push Docker image to Docker Hub
        run: |
          docker push docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/cookscorner_repo_docker:latest
